import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../core/theme.dart';

const _kPrivacyAcceptedKey = 'privacy_notice_accepted_v1';

/// Returns true if the user has already accepted the privacy notice.
Future<bool> hasAcceptedPrivacy() async {
  final prefs = await SharedPreferences.getInstance();
  return prefs.getBool(_kPrivacyAcceptedKey) ?? false;
}

/// Marks the privacy notice as accepted.
Future<void> _acceptPrivacy() async {
  final prefs = await SharedPreferences.getInstance();
  await prefs.setBool(_kPrivacyAcceptedKey, true);
}

/// Shows the privacy notice dialog if the user has not yet accepted it.
/// Returns only after the user taps Acknowledge.
Future<void> showPrivacyNoticeIfNeeded(BuildContext context) async {
  final accepted = await hasAcceptedPrivacy();
  if (accepted) return;
  if (!context.mounted) return;

  await showDialog<void>(
    context: context,
    barrierDismissible: false,
    builder: (ctx) => const _PrivacyNoticeDialog(),
  );
}

class _PrivacyNoticeDialog extends StatelessWidget {
  const _PrivacyNoticeDialog();

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
      title: Row(
        children: [
          Container(
            padding: const EdgeInsets.all(8),
            decoration: BoxDecoration(
              color: AppTheme.primaryColor.withValues(alpha: 0.1),
              borderRadius: BorderRadius.circular(8),
            ),
            child: const Icon(Icons.shield_outlined,
                color: AppTheme.primaryColor, size: 24),
          ),
          const SizedBox(width: 12),
          const Expanded(
            child: Text(
              'Privacy & Data Notice',
              style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18),
            ),
          ),
        ],
      ),
      content: SizedBox(
        width: double.maxFinite,
        child: SingleChildScrollView(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisSize: MainAxisSize.min,
            children: [
              _section(
                icon: Icons.lock_outline,
                color: AppTheme.successColor,
                title: 'All Data Stays On This Device',
                body:
                    'NeuroScale Pro stores all patient data exclusively on this device using encrypted local storage. No patient information is transmitted to any server or third party.',
              ),
              const SizedBox(height: 14),
              _section(
                icon: Icons.people_outline,
                color: AppTheme.primaryColor,
                title: 'Patient Confidentiality',
                body:
                    'This application is intended for use by licensed healthcare professionals only. All patient information entered must be handled in compliance with your institution\'s data protection and patient confidentiality policies.',
              ),
              const SizedBox(height: 14),
              _section(
                icon: Icons.smart_toy_outlined,
                color: AppTheme.accentColor,
                title: 'AI-Generated Content',
                body:
                    'Clinical summaries, severity ratings, and drug suggestions are generated by rule-based algorithms for reference only. They do NOT replace clinical judgment. Always verify all recommendations with qualified medical expertise.',
              ),
              const SizedBox(height: 14),
              _section(
                icon: Icons.mic_outlined,
                color: AppTheme.warningColor,
                title: 'Microphone Access',
                body:
                    'Voice input is used solely for scoring psychiatric scales hands-free during patient assessments. Audio is processed by the device\'s speech engine and is never recorded or stored.',
              ),
              const SizedBox(height: 14),
              _section(
                icon: Icons.warning_amber_outlined,
                color: AppTheme.dangerColor,
                title: 'Clinical Responsibility',
                body:
                    'The clinician using this application bears full clinical and legal responsibility for all patient care decisions. NeuroScale Pro is a decision-support tool, not a diagnostic instrument.',
              ),
              const SizedBox(height: 12),
              Container(
                padding: const EdgeInsets.all(10),
                decoration: BoxDecoration(
                  color: AppTheme.primaryColor.withValues(alpha: 0.05),
                  borderRadius: BorderRadius.circular(8),
                  border: Border.all(
                      color: AppTheme.primaryColor.withValues(alpha: 0.2)),
                ),
                child: const Text(
                  'By tapping "I Understand & Accept" you confirm that you are a '
                  'licensed healthcare professional and agree to use this application '
                  'responsibly in accordance with applicable regulations.',
                  style: TextStyle(fontSize: 12, color: Colors.grey),
                ),
              ),
            ],
          ),
        ),
      ),
      actions: [
        SizedBox(
          width: double.infinity,
          child: ElevatedButton.icon(
            icon: const Icon(Icons.check_circle_outline),
            label: const Text(
              'I Understand & Accept',
              style: TextStyle(fontWeight: FontWeight.bold),
            ),
            style: ElevatedButton.styleFrom(
              padding: const EdgeInsets.symmetric(vertical: 14),
              shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(10)),
            ),
            onPressed: () async {
              await _acceptPrivacy();
              if (context.mounted) Navigator.pop(context);
            },
          ),
        ),
      ],
    );
  }

  Widget _section({
    required IconData icon,
    required Color color,
    required String title,
    required String body,
  }) {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Container(
          margin: const EdgeInsets.only(top: 2),
          padding: const EdgeInsets.all(6),
          decoration: BoxDecoration(
            color: color.withValues(alpha: 0.1),
            borderRadius: BorderRadius.circular(6),
          ),
          child: Icon(icon, color: color, size: 18),
        ),
        const SizedBox(width: 10),
        Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(title,
                  style: TextStyle(
                      fontWeight: FontWeight.w600,
                      fontSize: 13,
                      color: color)),
              const SizedBox(height: 3),
              Text(body,
                  style: const TextStyle(fontSize: 12.5, height: 1.4)),
            ],
          ),
        ),
      ],
    );
  }
}
